### ISSUE TITLE
Remove google credentials, if they are not in use

### ISSUE THREAD

**Issue by Matsuuu** [data-science-institute-nuig/MyCovidSymptoms.ie#1]
Hello!

Cool to see that you're interested in fevermap.

Could you remove google API credentials from the front end, since they don't seem to be in use :)
Thanks !

- Matsu, Dev @ Fevermap

**Comment by carlostighe** [comment]
Hey @Matsuuu 
They have been removed in the current project but they do exist in an historical commit. 
Ill look into removing that.

**Comment by Matsuuu** [comment]
Cheers! :)

**Comment by carlostighe** [comment]
Good morning @Matsuuu 
I have a question. Is it an issue for you guys if the api credentials are in the commit history even though they have been removed from current app? 
Looking into removing historical commits and its seems the solution to removing commits could cause merge issues for the team

**Comment by Matsuuu** [comment]
Heya @carlostighe .

It's not an issue, if the creds are in the history. I received an email that our credentials were used in this project, and didn't check if it was a past version or present.

No need to rewrite history.

**Comment by carlostighe** [comment]
Great @Matsuuu. Thank you, and thanks for your work in fevermap.
